apiVersion: v1
kind: Service
metadata:
  name: phishing-detection-service
spec:
  selector:
    app: phishing-detection
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
